# Generated by Django 5.0.3 on 2024-03-26 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Checking_acc',
            fields=[
                ('bank_acc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bankapp.bank_acc')),
                ('last_transaction', models.DateField()),
            ],
            bases=('bankapp.bank_acc',),
        ),
        migrations.CreateModel(
            name='Savings_acc',
            fields=[
                ('bank_acc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bankapp.bank_acc')),
            ],
            bases=('bankapp.bank_acc',),
        ),
    ]
