# Generated by Django 5.0.3 on 2024-03-27 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.PositiveIntegerField(default='', primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('Name', models.CharField(default='', max_length=20)),
                ('Age', models.IntegerField(blank=True)),
                ('Address', models.CharField(default=None, max_length=25)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.DeleteModel(
            name='Customrs',
        ),
    ]
