# Generated by Django 5.0.3 on 2024-03-27 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClientsOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('each_date', models.DateField()),
                ('OrderNumber', models.CharField(max_length=11, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PManager.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CostPerItem', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ProName', models.CharField(max_length=50)),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PManager.manufacture')),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PManager.clients')),
                ('client_oroder', models.ManyToManyField(to='PManager.clientsorders')),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PManager.manufacture')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PManager.product')),
            ],
        ),
    ]
