# Generated by Django 5.0.3 on 2024-03-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factor',
            old_name='client_oroder',
            new_name='client_order',
        ),
    ]
