# Generated by Django 5.0.3 on 2024-04-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarCade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='manufacturer',
            new_name='manufacture',
        ),
        migrations.AddField(
            model_name='type',
            name='addingType',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
