# Generated by Django 5.0.3 on 2024-04-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarCade', '0002_rename_manufacturer_car_manufacture_type_addingtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='addingType',
        ),
    ]
