# Generated by Django 5.0.3 on 2024-04-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarCade', '0003_remove_type_addingtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='addingTypes',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
