# Generated by Django 5.0.3 on 2024-04-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarCade', '0004_type_addingtypes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufacturer',
            new_name='Manufacture',
        ),
        migrations.AlterField(
            model_name='type',
            name='addingTypes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(blank=True, choices=[('ns', 'not set'), ('f', 'SUV'), ('ha', 'Hatchback'), ('cp', 'Coupe'), ('nc', 'Convertible'), ('s', 'Sedan'), ('spc', 'Sports car'), ('p', 'Pickup'), ('m', 'MPV'), ('cc', 'City car'), ('ec', 'Electric cars'), ('fc', 'Family car'), ('hy', 'Hybrid'), ('lc', 'Luxury car'), ('mc', 'Microcar'), ('pc', 'Premium Compact'), ('sc', 'Supercar'), ('v', 'Van'), ('four', '4x4'), ('cu', 'CUV')], help_text="Car's Type (e.g. SUV)", max_length=100, null=True),
        ),
    ]
