# Generated by Django 5.0.3 on 2024-04-05 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarCade', '0006_remove_type_addingtypes_manufacture_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacture',
            name='type',
        ),
        migrations.AddField(
            model_name='type',
            name='manufacture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CarCade.manufacture'),
        ),
    ]
